### ISSUE TITLE
error with custom_themes

### ISSUE THREAD

**Issue by WadeDavis** [briandconnelly/ggplot2bdc#5]
Hi Brian,
I'm primarily a lattice user, so pardon me if I've missed something obvious when trying to use your custom themes....

When running any of the examples, I receive the following message:
```Error in (function (el, elname)  : 
  "plot.subtitle" is not a valid theme element name.```
When I re-rerun the code without the `+theme_bdc_foo` part, no error is issued

My sessionInfo()
```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5     dplyr_0.5.0      ggplot2_2.1.0    ggplot2bdc_0.2.1

loaded via a namespace (and not attached):
 [1] colorspace_1.2-6 scales_0.4.0     R6_2.1.2         assertthat_0.1   plyr_1.8.4       DBI_0.4-1       
 [7] tools_3.3.1      gtable_0.2.0     tibble_1.0       Rcpp_0.12.5      grid_3.3.1       munsell_0.4.3   
```

Thanks for any advice,
Wade

**Comment by briandconnelly** [comment]
Sorry about this. The problem is that I updated the theme to support a feature (plot subtitles) that's in the development version of ggplot, but not in the released version. I had thought that ggplot would just ignore this, but that doesn't seem to be the case.

There doesn't seem to be a way to specify a release for `install_github`, but you'd like to use a previous version of the package, you can download [version 0.1.7](https://github.com/briandconnelly/ggplot2bdc/releases/tag/v0.1.7), which should work very similarly to how they're described in the README.

Hopefully a new version of ggplot will be released soon that includes the subtitle element.

**Comment by briandconnelly** [comment]
I've updated the themes to avoid subtitles and captions when those aren't supported. If you can, please update the package and let me know if you still get this error.

**Comment by WadeDavis** [comment]
I updated the package and all of the themes work now except theme_bdc_microtiter, which was the one main one I was interested in. It retruns the same error as before. I saw that theme_bdc_microtiter is mostly a wrapper for theme_bdc_grey and how you modified it, so I tried that:

```


theme_bdc_microtiter2<-function (base_size = 12, base_family = "") 
{
    t<-theme_bdc_grey(base_size = base_size, base_family = base_family, 
        grid.x = FALSE, grid.y = FALSE, gridmin.x = FALSE, gridmin.y = FALSE, 
        ticks.x = FALSE, ticks.y = FALSE, pmargin = base_size/2) %+replace% 
        theme(panel.margin = unit(0, units = "pt"), axis.title = element_text(size = 0), 
            axis.text = element_text(size = rel(1), face = "bold"), 
            axis.text.y = element_text(margin = margin(r = 0.4 * 
                base_size, l = 0.4 * base_size)), axis.text.x = element_text(margin = margin(t = 0.4 * 
                base_size, b = 0.4 * base_size)), axis.ticks.length = unit(0, 
                "pt"), legend.position = "bottom", legend.direction = "horizontal", 
            legend.box = "vertical", legend.margin = unit(6, 
                "pt"), plot.title = element_text(size = rel(1.2), 
                face = "bold", hjust = 0.5, margin = margin(b = (base_size/2) * 
                  1.2)))
if (gg_supports_theme_attribute("plot.subtitle")) {
        t <- t + theme(plot.subtitle = element_text(size = rel(0.8), 
            color = "grey40", face = "italic", hjust = 0, margin = margin(b = (base_size/2) * 
                1.2)))
    }
    if (gg_supports_theme_attribute("plot.caption")) {
        t <- t + theme(plot.caption = element_text(size = rel(0.7), 
            color = "grey40", face = "plain", hjust = 0, margin = margin(b = base_size * 
                0.4, t = base_size * 0.4, r = 0, l = 0)))
    }
    t
}

```
No error is returned now, but I don't have a positive control test to see if it will produce the subititle because I am not running the `dev` version of ggplot2. Hopefully it works for that.

**Comment by briandconnelly** [comment]
Of course, the one theme that I didn't test with both versions of ggplot. Fixed this and pushed a new version.

**Comment by WadeDavis** [comment]
Thanks, works great now.
